### ISSUE TITLE
KeyError: 'txt'

### ISSUE THREAD

**Issue by hack-r** [stanfordio/gogettr#15]
Similar to [Issue #13 ](https://github.com/stanfordio/gogettr/issues/13) I receive the following KeyError message with the "all" command (plain or with --rev) after the first scraped post:

```
    if data["data"]["txt"] == "Content Not Found":
KeyError: 'txt'
```

If it's unclear how to resolve the error then reviewing this [PHP-based API client](https://github.com/beeyev/gettr-api-client-php) on GitHub may be useful, as I'm able to scrape with that without any issues.

_Unrelated:_ The quoted description contained in this project's "About" and README.md, i.e. '"non-bias [sic] social network,"' attempts to emphasize an ephemeral grammatical error in the App Store description that no longer exists, highlighting the project maintainers' condescension. This reflects poorly on StanfordIO and Stanford University.

**Comment by KonradIT** [comment]
Are you running from source or from a pip installation? There's no current release with my fix out on GH, so no automatic build to Pypi.

**Comment by milesmcc** [comment]
@KonradIT thanks for the reminder. I just published v0.7.0 with your changes to PyPI.

**Comment by hack-r** [comment]
I thought it was cloned but I haven't tested it to confirm due to it sounding like it doesn't matter since the changes were just pushed to PyPi anyway. Quick work! Happy new year, cheers.

If you need me to verify the solution lmk.

**Comment by hack-r** [comment]
Yes, v0.7.0 works well, cheers. Happy new year.
