### ISSUE TITLE
Hashtags don't really make sense

### ISSUE THREAD

**Issue by TheGitHubGuy1** [stanfordio/gogettr#18]
Hi,

The hashtags don't really make sense as they are full sentences starting with a hashtag. Strange, but it behaves the same way on the mobile before entering a key. Those hashtags won't work because of the spaces. What's the API you are using? i'd like to be able to provide a letter for the top hashstags for that letter.

**Comment by lxcode** [comment]
We're using the hashtag/suggest API, which is what Gettr currently uses for trending news, not actual hashtags. Not much we can do about that.
