### ISSUE TITLE
Retrieving all followers/following for an account

### ISSUE THREAD

**Issue by AminMekacher** [stanfordio/gogettr#19]
Hey!

I have been trying to play around with the API to get the followers of some specific accounts, but I was wondering if GoGettr is able to get the whole list of followers for any account? I've been running some tests with a few accounts, and I usually get a fraction of the account's followers (for example, I get 1035 followers for @sloan4america, whereas he's supposed to have about 26k followers). I took a look at the gogettr.log file, and I noticed that the followers are retrieved by batches of 500 with the offset parameter. However, it seems that each batch generally has 20 followers. It may be that I am not using correctly, in which case please feel free to correct me.

Btw thanks again for all your hard work to develop this API, it is really an invaluable resource!

**Comment by milesmcc** [comment]
Should be fixed in https://github.com/stanfordio/gogettr/commit/b93c342440a2723bb320b650de56a791cf3ed70f — double check you're running the most recent version (v0.8.0)?
