### ISSUE TITLE
Search returning a 500 error

### ISSUE THREAD

**Issue by apilover12321** [stanfordio/gogettr#30]
Searches that worked in the past no long work.

Using parameters:
{'max': 20, 'q': 'openai', 'sort': 'recent', 'offset': 0}

I get:

```
{"_t":"xresp","rc":"ERR","error":{"_t":"xerr","code":"E_API_ERROR","emsg":"An error occurred","args":[]}}'}
```

**Comment by apilover12321** [comment]
Seems like a temporary problem - it's working again.  Sorry.

**Comment by milesmcc** [comment]
No worries!
