### ISSUE TITLE
Gettr search returns 500 error

### ISSUE THREAD

**Issue by hauserns-vs** [stanfordio/gogettr#31]
For the past 5 days, I get the following response for every search query:

request:
```
 GET /u/posts/srch/phrase with params {'max': 20, 'q': 'openai', 'sort': 'recent', 'offset': 0}
```

response:
```
{"_t":"xresp","rc":"ERR","error":{"_t":"xerr","code":"E_API_ERROR","emsg":"An error occurred","args":[]}}'}
```

Please let me know if you're experiencing the same thing or what I'm doing wrong.

**Comment by DavidSimonRothschild** [comment]
I was running this code:

client = PublicClient()

# Search for posts containing the word "Python"
posts = client.search('Trump', max=5)

# Print the posts
for post in posts:
    print(post)

And got this error message:

 Unable to pull from API: {'status_code': 500}.

seems to be a similar problem with the API, or what do you mean?

**Comment by itsgorain** [comment]
I am getting the same error. It would be great to have this working.

`WARNING:gogettr.api:Unable to pull from API: {'status_code': 500}. Waiting 4 seconds before retrying (1/3)...
WARNING:gogettr.api:Unable to pull from API: {'status_code': 500}. Waiting 16 seconds before retrying (2/3)...
WARNING:gogettr.api:Unable to pull from API: {'status_code': 500}. Waiting 64 seconds before retrying (3/3)...`

**Comment by milesmcc** [comment]
Seems like some sort of change on Gettr's end. I don't currently have bandwidth to investigate/update the tool but would gladly take a PR that does so.

**Comment by saghiyeganeh** [comment]
@milesmcc Happy to help update the code to adapt the new changes on Gettr. Any chance you could provide insights on how to find the parameters for the new Gettr endpoints? The new endpoint seems to be working but needs a new set of parameters. Many thanks!

**Comment by saghiyeganeh** [comment]
Actually here is an example of pulling data from the v2 endpoint:

```
import requests

headers = {
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
}

data = {
    'content': {
        'incl': 'poststats|shared|liked|posts|userinfo|followings|followers',
        'q': 'washingtonpost.com', 
        'offset': 0,
        'max': 20,
        'sort': '/u/search/v2/post'
    }
}

response = requests.post('https://gettr.com/api/u/search/v2/post', headers=headers, json=data)

r=response.json()
```

**Comment by milesmcc** [comment]
Hey! That looks reasonable to me — to clarify, have you answered the original question?

(Re: finding the parameters, I typically just log on to the platform and watch the network traffic in the developer console.)

**Comment by saghiyeganeh** [comment]
Hey @milesmcc yes, that was what I was looking for. It seems it needs kind of proxy rotation to avoid being blocked thought.

**Comment by milesmcc** [comment]
Yep, that seems right; rotation is likely necessary.
