### ISSUE TITLE
pypi install not working

### ISSUE THREAD

**Issue by maxzzze** [stanfordio/gogettr#4]
```bash
➜  ~ pip install gogettr
ERROR: Could not find a version that satisfies the requirement gogettr
ERROR: No matching distribution found for gogettr
```

**Comment by milesmcc** [comment]
What is your `pip --version`? Perhaps `pip3 install gogettr` would work?

**Comment by maxzzze** [comment]
```bash
➜  ~ pip3 --version
pip 21.1.3 from /Users/untitled/anaconda3/lib/python3.7/site-packages/pip (python 3.7)
➜  ~ pip3 install gogettr
ERROR: Could not find a version that satisfies the requirement gogettr (from versions: none)
ERROR: No matching distribution found for gogettr
```

**Comment by maxzzze** [comment]
do you have a link to the pypi repo? what is the current version tag registered there?

**Comment by milesmcc** [comment]
v0.3.1 live on PyPI: https://pypi.org/project/gogettr/

**Comment by milesmcc** [comment]
Oh, it's because you have Python 3.7. We currently require >3.8. I'll change that.

**Comment by milesmcc** [comment]
On second thought, we do use some Python 3.8 specific features (e.g., literal typing). Maybe the best course of action here is to add a note to the README mentioning that >=3.8 is required?

**Comment by maxzzze** [comment]
> On second thought, we do use some Python 3.8 specific features (e.g., literal typing). Maybe the best course of action here is to add a note to the README mentioning that >=3.8 is required?

yep sounds good
