### ISSUE TITLE
Getting a specific post's comments

### ISSUE THREAD

**Issue by KonradIT** [stanfordio/gogettr#5]
I'm working on this feature on [my branch](https://github.com/KonradIT/gogettr/tree/comments_from_post).

Feedback welcome, maybe it's better if I do the iteration using a `while content is available` loop.

**Comment by milesmcc** [comment]
Awesome, looks great so far. Feel free to open a PR once it's ready. I think the way you do the iteration right now is fine — `get_paginated` will end when content becomes unavailable.

**Comment by KonradIT** [comment]
Perfect, opening a PR now. I've tried it and it works for a thread with 400+ comments.

**Comment by milesmcc** [comment]
Closed in #6!
